// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCyI4XWK5B_cPXTgHd5sZouyMTKxPXrKME',
    appId: '1:278818755713:web:28689504c33906197b2980',
    messagingSenderId: '278818755713',
    projectId: 'mp-mount',
    authDomain: 'mp-mount.firebaseapp.com',
    storageBucket: 'mp-mount.appspot.com',
    measurementId: 'G-EVP8CRPGD5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB1OUj7HPFRCg05EGRfU4vwU5XNxTnfGi0',
    appId: '1:278818755713:android:6e3277d2250d3b5e7b2980',
    messagingSenderId: '278818755713',
    projectId: 'mp-mount',
    storageBucket: 'mp-mount.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDFacR4ZvMpPyAWfgq_DBY6Qj0MOKuxbOY',
    appId: '1:278818755713:ios:6209004ae20d8d027b2980',
    messagingSenderId: '278818755713',
    projectId: 'mp-mount',
    storageBucket: 'mp-mount.appspot.com',
    iosBundleId: 'com.example.flutterApplicationMount',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDFacR4ZvMpPyAWfgq_DBY6Qj0MOKuxbOY',
    appId: '1:278818755713:ios:d9dbf70bc8f9a2ad7b2980',
    messagingSenderId: '278818755713',
    projectId: 'mp-mount',
    storageBucket: 'mp-mount.appspot.com',
    iosBundleId: 'com.example.flutterApplicationMount.RunnerTests',
  );
}
